### ISSUE TITLE
支持markdown代码行号?

### ISSUE THREAD

**Issue by zhaoqingqing** [imgss/cnblogs-mdEditor#1]
想找找看支持博客园markdown代码显示行号的插件。

如果是markdown编辑器，推荐typora：https://typora.io/  ，用于编辑markdown很赞。

**Comment by zhaoqingqing** [comment]
建议在readme中配几张截图，能让读者更快上手。

**Comment by imgss** [comment]
谢谢你的建议，readme确实写的有点糙😓
编辑器是基于codeMirror实现的，之前有写过[一篇文章](https://www.cnblogs.com/imgss/p/9368869.html)介绍过
目前支持的功能有:

- 生成目录
- 编辑器全屏
- 设置主题（黑白）和字号大小
- 拖拽图片上传
都是根据我的需求来的。。显示行号会加上去的，之前没有加是因为我不是很需要

**Comment by zhaoqingqing** [comment]
nice.
