### ISSUE TITLE
Can you seal the plug-in

### ISSUE THREAD

**Issue by zhangweibo3692** [imgss/cnblogs-mdEditor#2]
Every time I open my browser, it reminds me that the plugin is not safe. Packaging... Thanks

**Comment by imgss** [comment]
@zhangweibo3692 sure，I will do this as soon as possible

**Comment by imgss** [comment]
已提交一个版本到应用商店，可以到[这里](https://chrome.google.com/webstore/detail/cnblogsmdeditor/dmohalpippgmopnbpnknmapokjdkifmc)查看
